# Generated by Django 4.2.5 on 2023-09-18 04:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_title", models.CharField(max_length=500)),
                ("news_description", tinymce.models.HTMLField()),
            ],
        ),
    ]
