# Generated by Django 4.2.5 on 2023-09-18 05:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug_title",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                null=True,
                populate_from=models.CharField(max_length=500),
                unique=True,
            ),
        ),
    ]
