# Generated by Django 4.2.5 on 2023-09-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_slug_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="slug_title",
            new_name="slug",
        ),
    ]
