# Generated by Django 4.2.5 on 2023-09-18 06:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_rename_slug_title_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="news_title", unique=True
            ),
        ),
    ]
