# Generated by Django 4.2.5 on 2023-09-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_news_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_image",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="news/"
            ),
        ),
    ]
