# Generated by Django 4.2.5 on 2023-09-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_icon",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_title",
            field=models.CharField(max_length=500),
        ),
    ]
